import 'package:flutter/material.dart';
import '../main.dart';
class ProfileSetupScreen extends StatefulWidget { const ProfileSetupScreen({super.key}); @override State<ProfileSetupScreen> createState() => _ProfileSetupScreenState(); }
class _ProfileSetupScreenState extends State<ProfileSetupScreen> {
  final _name = TextEditingController(); String _gender = '남성'; String _mbti = 'ENFP';
  final _mbtis = ['ISTJ','ISFJ','INFJ','INTJ','ISTP','ISFP','INFP','INTP','ESTP','ESFP','ENFP','ENTP','ESTJ','ESFJ','ENFJ','ENTJ'];
  final _hobbies = ['맛집탐방','카페투어','영화보기','산책','게임','운동','드라이브','음악감상','여행'];
  List<String> _selHobbies = []; bool _voiceAdded = false;
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: Colors.white, appBar: AppBar(title: const Text('프로필 완성하기', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)), backgroundColor: Colors.white, elevation: 0), body: ListView(padding: const EdgeInsets.all(24), children: [
    Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: Colors.grey.shade50, borderRadius: BorderRadius.circular(8)), child: const Row(children: [Icon(Icons.security, color: Color(0xFFFF3B30), size: 16), SizedBox(width: 8), Text('24시간 안전 관리자 검수 중입니다.', style: TextStyle(color: Colors.grey, fontSize: 12))])), const SizedBox(height: 24),
    const Text('프로필 사진 (최소 2장)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    Row(children: [ _photoBox(true, true), const SizedBox(width:8), _photoBox(false, true), const SizedBox(width:8), _photoBox(false, false) ]), const SizedBox(height: 24),
    const Text('닉네임', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    TextField(controller: _name, decoration: InputDecoration(hintText: '자신을 잘 표현하는 닉네임', border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)), contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14))), const SizedBox(height: 24),
    const Text('성별', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    Row(children: ['남성', '여성'].map((g) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 8), child: OutlinedButton(onPressed: () => setState(() => _gender = g), style: OutlinedButton.styleFrom(side: BorderSide(color: _gender == g ? const Color(0xFFFF3B30) : Colors.grey.shade300, width: _gender == g ? 2 : 1), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)), padding: const EdgeInsets.symmetric(vertical: 14)), child: Text(g, style: TextStyle(color: _gender == g ? const Color(0xFFFF3B30) : Colors.grey, fontWeight: FontWeight.bold)))))).toList()), const SizedBox(height: 24),
    const Text('MBTI', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    DropdownButtonFormField<String>(value: _mbti, decoration: InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.circular(12))), items: _mbtis.map((m) => DropdownMenuItem(value: m, child: Text(m))).toList(), onChanged: (v) => setState(() => _mbti = v!)), const SizedBox(height: 24),
    const Text('관심사 태그 (최대 3개)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    Wrap(spacing: 8, runSpacing: 8, children: _hobbies.map((h) => FilterChip(label: Text(h), selected: _selHobbies.contains(h), onSelected: (v) { setState(() { if(v && _selHobbies.length < 3) _selHobbies.add(h); else if(!v) _selHobbies.remove(h); }); }, selectedColor: const Color(0xFFFF3B30), labelStyle: TextStyle(color: _selHobbies.contains(h) ? Colors.white : Colors.black))).toList()), const SizedBox(height: 24),
    const Text('목소리 소개 (선택)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8),
    InkWell(onTap: ()=>setState(()=>_voiceAdded=!_voiceAdded), child: Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(border: Border.all(color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey.shade300), borderRadius: BorderRadius.circular(12), color: _voiceAdded ? const Color(0xFFFFF5F5) : Colors.white), child: Row(children: [Icon(_voiceAdded ? Icons.mic : Icons.mic_none, color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey), const SizedBox(width: 12), Text(_voiceAdded ? '목소리가 등록되었습니다' : '내 목소리로 3초 어필하기', style: TextStyle(color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey, fontWeight: FontWeight.bold))]))), const SizedBox(height: 48),
    ElevatedButton(onPressed: () => Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (_) => const MainNavigation()), (_) => false), style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFFFF3B30), minimumSize: const Size(double.infinity, 56), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))), child: const Text('위피 시작하기', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16))),
  ]));
  Widget _photoBox(bool isMain, bool isRequired) => Expanded(child: AspectRatio(aspectRatio: 3/4, child: Container(decoration: BoxDecoration(color: Colors.grey.shade100, borderRadius: BorderRadius.circular(12), border: Border.all(color: isMain ? const Color(0xFFFF3B30) : Colors.grey.shade300, width: isMain?2:1)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(Icons.add_photo_alternate, color: isMain ? const Color(0xFFFF3B30) : Colors.grey), const SizedBox(height: 4), if(isMain) const Text('대표', style: TextStyle(color: Color(0xFFFF3B30), fontSize: 10, fontWeight: FontWeight.bold)) else if(isRequired) const Text('필수', style: TextStyle(color: Colors.grey, fontSize: 10))]))));
}
