import 'package:flutter/material.dart';
import '../main.dart';
class ProfileSetupScreen extends StatefulWidget { const ProfileSetupScreen({super.key}); @override State<ProfileSetupScreen> createState() => _ProfileSetupScreenState(); }
class _ProfileSetupScreenState extends State<ProfileSetupScreen> {
  final _name = TextEditingController(); 
  String _gender = ''; String _age = ''; bool _isPassVerified = false;
  String _mbti = 'ENFP'; final _mbtis = ['ISTJ','ISFJ','INFJ','INTJ','ISTP','ISFP','INFP','INTP','ESTP','ESFP','ENFP','ENTP','ESTJ','ESFJ','ENFJ','ENTJ'];
  String _job = '선택안함'; final _jobs = ['선택안함', '대기업', '공기업', '전문직(의사/변호사)', 'IT/개발', '스타트업', '프리랜서', '사업가', '학생'];
  String _income = '선택안함'; final _incomes = ['선택안함', '5천만원 이상', '7천만원 이상', '1억원 이상', '3억원 이상', '5억원 이상']; bool _incomeVerified = false;
  final _hobbies = ['맛집탐방','카페투어','영화보기','산책','게임','운동','드라이브','음악감상','여행']; List<String> _selHobbies = []; bool _voiceAdded = false;

  void _verifyPass() {
    showDialog(context: context, barrierDismissible: false, builder: (ctx) => AlertDialog(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), content: const Column(mainAxisSize: MainAxisSize.min, children: [CircularProgressIndicator(color: Color(0xFFFF3B30)), SizedBox(height: 16), Text('PASS 본인인증 진행중...', style: TextStyle(fontWeight: FontWeight.bold))])));
    Future.delayed(const Duration(seconds: 2), () {
      Navigator.pop(context);
      setState(() { _isPassVerified = true; _name.text = '안시향'; _gender = '여성'; _age = '26세 (98년생)'; });
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('PASS 인증 완료! 나이/성별이 자동 입력되었습니다.'), backgroundColor: Colors.green));
    });
  }

  void _verifyIncome() {
    showDialog(context: context, barrierDismissible: false, builder: (ctx) => AlertDialog(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), content: const Column(mainAxisSize: MainAxisSize.min, children: [CircularProgressIndicator(color: Color(0xFFFF3B30)), SizedBox(height: 16), Text('원천징수영수증 검토중...', style: TextStyle(fontWeight: FontWeight.bold))])));
    Future.delayed(const Duration(seconds: 2), () {
      Navigator.pop(context); setState(() { _incomeVerified = true; });
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('소득 인증이 승인되었습니다! 뱃지가 부여됩니다.'), backgroundColor: Colors.blue));
    });
  }

  @override Widget build(BuildContext context) => Scaffold(backgroundColor: Colors.white, appBar: AppBar(title: const Text('프로필 완성하기', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)), backgroundColor: Colors.white, elevation: 0), body: ListView(padding: const EdgeInsets.all(24), children: [
    Container(padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: Colors.grey.shade50, borderRadius: BorderRadius.circular(8)), child: const Row(children: [Icon(Icons.security, color: Color(0xFFFF3B30), size: 16), SizedBox(width: 8), Text('데이팅 앱 필수: 24시간 안전 관리자 검수 중입니다.', style: TextStyle(color: Colors.grey, fontSize: 12))])), const SizedBox(height: 24),
    const Text('1. 신뢰도 인증 (필수/선택)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Color(0xFFFF3B30))), const SizedBox(height: 16),
    InkWell(onTap: _isPassVerified ? null : _verifyPass, child: Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(border: Border.all(color: _isPassVerified ? Colors.green : Colors.grey.shade300), borderRadius: BorderRadius.circular(12), color: _isPassVerified ? Colors.green.withOpacity(0.05) : Colors.white), child: Row(children: [Icon(Icons.verified_user, color: _isPassVerified ? Colors.green : Colors.grey), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('PASS 본인인증 (필수)', style: TextStyle(fontWeight: FontWeight.bold, color: _isPassVerified ? Colors.green : Colors.black87)), if (_isPassVerified) Text('$_name | $_gender | $_age', style: const TextStyle(fontSize: 12, color: Colors.green))])), if (!_isPassVerified) const Text('인증하기', style: TextStyle(color: Color(0xFFFF3B30), fontWeight: FontWeight.bold))]))), const SizedBox(height: 12),
    const Text('프로필 사진 (최소 2장)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8), Row(children: [ _photoBox(true, true), const SizedBox(width:8), _photoBox(false, true), const SizedBox(width:8), _photoBox(false, false) ]), const SizedBox(height: 24),
    const Text('2. 상세 정보', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Color(0xFFFF3B30))), const SizedBox(height: 16),
    const Text('직업', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8), DropdownButtonFormField<String>(value: _job, decoration: InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.circular(12))), items: _jobs.map((m) => DropdownMenuItem(value: m, child: Text(m))).toList(), onChanged: (v) => setState(() => _job = v!)), const SizedBox(height: 24),
    Row(children: [const Text('소득 수준 (선택)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const Spacer(), if (_income != '선택안함' && !_incomeVerified) InkWell(onTap: _verifyIncome, child: const Text('인증 서류 제출', style: TextStyle(color: Colors.blue, fontWeight: FontWeight.bold, fontSize: 13)))]), const SizedBox(height: 8), DropdownButtonFormField<String>(value: _income, decoration: InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.circular(12))), items: _incomes.map((m) => DropdownMenuItem(value: m, child: Text(m))).toList(), onChanged: (v) => setState(() => _income = v!)), if (_incomeVerified) const Padding(padding: EdgeInsets.only(top: 8), child: Row(children: [Icon(Icons.check_circle, color: Colors.blue, size: 16), SizedBox(width: 4), Text('국세청 소득 증빙 완료', style: TextStyle(color: Colors.blue, fontSize: 12, fontWeight: FontWeight.bold))])), const SizedBox(height: 24),
    const Text('MBTI', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8), DropdownButtonFormField<String>(value: _mbti, decoration: InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.circular(12))), items: _mbtis.map((m) => DropdownMenuItem(value: m, child: Text(m))).toList(), onChanged: (v) => setState(() => _mbti = v!)), const SizedBox(height: 24),
    const Text('관심사 태그 (최대 3개)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8), Wrap(spacing: 8, runSpacing: 8, children: _hobbies.map((h) => FilterChip(label: Text(h), selected: _selHobbies.contains(h), onSelected: (v) { setState(() { if(v && _selHobbies.length < 3) _selHobbies.add(h); else if(!v) _selHobbies.remove(h); }); }, selectedColor: const Color(0xFFFF3B30), labelStyle: TextStyle(color: _selHobbies.contains(h) ? Colors.white : Colors.black))).toList()), const SizedBox(height: 24),
    const Text('목소리 소개 (선택)', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)), const SizedBox(height: 8), InkWell(onTap: ()=>setState(()=>_voiceAdded=!_voiceAdded), child: Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(border: Border.all(color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey.shade300), borderRadius: BorderRadius.circular(12), color: _voiceAdded ? const Color(0xFFFFF5F5) : Colors.white), child: Row(children: [Icon(_voiceAdded ? Icons.mic : Icons.mic_none, color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey), const SizedBox(width: 12), Text(_voiceAdded ? '목소리가 등록되었습니다' : '내 목소리로 3초 어필하기', style: TextStyle(color: _voiceAdded ? const Color(0xFFFF3B30) : Colors.grey, fontWeight: FontWeight.bold))]))), const SizedBox(height: 48),
    ElevatedButton(onPressed: () { if(!_isPassVerified) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('PASS 본인인증을 먼저 진행해주세요.'))); return; } Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (_) => const MainNavigation()), (_) => false); }, style: ElevatedButton.styleFrom(backgroundColor: _isPassVerified ? const Color(0xFFFF3B30) : Colors.grey, minimumSize: const Size(double.infinity, 56), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))), child: const Text('위피 시작하기', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)))]));
  Widget _photoBox(bool isMain, bool isRequired) => Expanded(child: AspectRatio(aspectRatio: 3/4, child: Container(decoration: BoxDecoration(color: Colors.grey.shade100, borderRadius: BorderRadius.circular(12), border: Border.all(color: isMain ? const Color(0xFFFF3B30) : Colors.grey.shade300, width: isMain?2:1)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(Icons.add_photo_alternate, color: isMain ? const Color(0xFFFF3B30) : Colors.grey), const SizedBox(height: 4), if(isMain) const Text('대표', style: TextStyle(color: Color(0xFFFF3B30), fontSize: 10, fontWeight: FontWeight.bold)) else if(isRequired) const Text('필수', style: TextStyle(color: Colors.grey, fontSize: 10))]))));
}
